### PR TITLE
sync doc translate：[API-Store/Readme/bindActionCreators/createStore]

### PR DESCRIPTION
**Pull request by rccoder**

### CODE REVIEW

**Comment by rccoder** [comment]
https://github.com/camsong/redux-in-chinese/issues/192

**Comment by rccoder** [comment]
https://github.com/camsong/redux-in-chinese/issues/190

**Comment by rccoder** [comment]
https://github.com/camsong/redux-in-chinese/issues/195

**Comment by rccoder** [comment]
https://github.com/camsong/redux-in-chinese/issues/191

**Comment by camsong** [comment]
Thanks for the awesome work, really appreciate it.

**Pull request merged**
